//! Generated by `cargo xtask sherpa-libs --pin` from the config structs of sherpa-onnx 1.13.8, the crate Cargo.lock
//! pins: do not edit. `cargo xtask sherpa-libs --check` fails when it is not what that version makes.
//!
//! Every field that takes a file, by its path from the config root it is in: the offline recognizer's model config
//! (`OfflineRecognizerConfig.model_config`) for speech to text, the offline TTS's (`OfflineTtsConfig.model`) for text
//! to speech, the voice activity detector's (`VadModelConfig`) for voice activity. What a sherpa-onnx build's file
//! keys name. If the crate derives serde for its configs one day, this table gives way to `serde_json::from_value`.
//!
//! And every field a call's argument may set through a build's `call_params`: a language, a task.

use sherpa_onnx::{OfflineModelConfig, OfflineTtsModelConfig, VadModelConfig};

/// The field of `OfflineRecognizerConfig.model_config` that `key` names, if it takes a file.
pub(in crate::backend::implementations::sherpa_onnx) fn stt_field<'a>(
    config: &'a mut OfflineModelConfig,
    key: &str,
) -> Option<&'a mut Option<String>> {
    Some(match key {
        "transducer.encoder" => &mut config.transducer.encoder,
        "transducer.decoder" => &mut config.transducer.decoder,
        "transducer.joiner" => &mut config.transducer.joiner,
        "paraformer.model" => &mut config.paraformer.model,
        "nemo_ctc.model" => &mut config.nemo_ctc.model,
        "whisper.encoder" => &mut config.whisper.encoder,
        "whisper.decoder" => &mut config.whisper.decoder,
        "tdnn.model" => &mut config.tdnn.model,
        "sense_voice.model" => &mut config.sense_voice.model,
        "moonshine.preprocessor" => &mut config.moonshine.preprocessor,
        "moonshine.encoder" => &mut config.moonshine.encoder,
        "moonshine.uncached_decoder" => &mut config.moonshine.uncached_decoder,
        "moonshine.cached_decoder" => &mut config.moonshine.cached_decoder,
        "moonshine.merged_decoder" => &mut config.moonshine.merged_decoder,
        "fire_red_asr.encoder" => &mut config.fire_red_asr.encoder,
        "fire_red_asr.decoder" => &mut config.fire_red_asr.decoder,
        "dolphin.model" => &mut config.dolphin.model,
        "zipformer_ctc.model" => &mut config.zipformer_ctc.model,
        "canary.encoder" => &mut config.canary.encoder,
        "canary.decoder" => &mut config.canary.decoder,
        "wenet_ctc.model" => &mut config.wenet_ctc.model,
        "omnilingual.model" => &mut config.omnilingual.model,
        "medasr.model" => &mut config.medasr.model,
        "funasr_nano.encoder_adaptor" => &mut config.funasr_nano.encoder_adaptor,
        "funasr_nano.llm" => &mut config.funasr_nano.llm,
        "funasr_nano.embedding" => &mut config.funasr_nano.embedding,
        "funasr_nano.tokenizer" => &mut config.funasr_nano.tokenizer,
        "fire_red_asr_ctc.model" => &mut config.fire_red_asr_ctc.model,
        "qwen3_asr.conv_frontend" => &mut config.qwen3_asr.conv_frontend,
        "qwen3_asr.encoder" => &mut config.qwen3_asr.encoder,
        "qwen3_asr.decoder" => &mut config.qwen3_asr.decoder,
        "qwen3_asr.tokenizer" => &mut config.qwen3_asr.tokenizer,
        "cohere_transcribe.encoder" => &mut config.cohere_transcribe.encoder,
        "cohere_transcribe.decoder" => &mut config.cohere_transcribe.decoder,
        "tokens" => &mut config.tokens,
        "bpe_vocab" => &mut config.bpe_vocab,
        "telespeech_ctc" => &mut config.telespeech_ctc,
        _ => return None,
    })
}

/// The field of `OfflineTtsConfig.model` that `key` names, if it takes a file.
pub(in crate::backend::implementations::sherpa_onnx) fn tts_field<'a>(
    config: &'a mut OfflineTtsModelConfig,
    key: &str,
) -> Option<&'a mut Option<String>> {
    Some(match key {
        "vits.model" => &mut config.vits.model,
        "vits.lexicon" => &mut config.vits.lexicon,
        "vits.tokens" => &mut config.vits.tokens,
        "vits.data_dir" => &mut config.vits.data_dir,
        "vits.dict_dir" => &mut config.vits.dict_dir,
        "matcha.acoustic_model" => &mut config.matcha.acoustic_model,
        "matcha.vocoder" => &mut config.matcha.vocoder,
        "matcha.lexicon" => &mut config.matcha.lexicon,
        "matcha.tokens" => &mut config.matcha.tokens,
        "matcha.data_dir" => &mut config.matcha.data_dir,
        "matcha.dict_dir" => &mut config.matcha.dict_dir,
        "kokoro.model" => &mut config.kokoro.model,
        "kokoro.voices" => &mut config.kokoro.voices,
        "kokoro.tokens" => &mut config.kokoro.tokens,
        "kokoro.data_dir" => &mut config.kokoro.data_dir,
        "kokoro.dict_dir" => &mut config.kokoro.dict_dir,
        "kokoro.lexicon" => &mut config.kokoro.lexicon,
        "kitten.model" => &mut config.kitten.model,
        "kitten.voices" => &mut config.kitten.voices,
        "kitten.tokens" => &mut config.kitten.tokens,
        "kitten.data_dir" => &mut config.kitten.data_dir,
        "zipvoice.tokens" => &mut config.zipvoice.tokens,
        "zipvoice.encoder" => &mut config.zipvoice.encoder,
        "zipvoice.decoder" => &mut config.zipvoice.decoder,
        "zipvoice.vocoder" => &mut config.zipvoice.vocoder,
        "zipvoice.data_dir" => &mut config.zipvoice.data_dir,
        "zipvoice.lexicon" => &mut config.zipvoice.lexicon,
        "pocket.lm_flow" => &mut config.pocket.lm_flow,
        "pocket.lm_main" => &mut config.pocket.lm_main,
        "pocket.encoder" => &mut config.pocket.encoder,
        "pocket.decoder" => &mut config.pocket.decoder,
        "pocket.text_conditioner" => &mut config.pocket.text_conditioner,
        "pocket.vocab_json" => &mut config.pocket.vocab_json,
        "pocket.token_scores_json" => &mut config.pocket.token_scores_json,
        "supertonic.duration_predictor" => &mut config.supertonic.duration_predictor,
        "supertonic.text_encoder" => &mut config.supertonic.text_encoder,
        "supertonic.vector_estimator" => &mut config.supertonic.vector_estimator,
        "supertonic.vocoder" => &mut config.supertonic.vocoder,
        "supertonic.tts_json" => &mut config.supertonic.tts_json,
        "supertonic.unicode_indexer" => &mut config.supertonic.unicode_indexer,
        "supertonic.voice_style" => &mut config.supertonic.voice_style,
        _ => return None,
    })
}

/// The field of `VadModelConfig` that `key` names, if it takes a file.
pub(in crate::backend::implementations::sherpa_onnx) fn vad_field<'a>(
    config: &'a mut VadModelConfig,
    key: &str,
) -> Option<&'a mut Option<String>> {
    Some(match key {
        "silero_vad.model" => &mut config.silero_vad.model,
        "ten_vad.model" => &mut config.ten_vad.model,
        _ => return None,
    })
}

/// The field of `OfflineRecognizerConfig.model_config` that `path` names, if a call's argument may set it.
pub(in crate::backend::implementations::sherpa_onnx) fn stt_option<'a>(
    config: &'a mut OfflineModelConfig,
    path: &str,
) -> Option<&'a mut Option<String>> {
    Some(match path {
        "whisper.language" => &mut config.whisper.language,
        "whisper.task" => &mut config.whisper.task,
        "canary.src_lang" => &mut config.canary.src_lang,
        "canary.tgt_lang" => &mut config.canary.tgt_lang,
        "sense_voice.language" => &mut config.sense_voice.language,
        "cohere_transcribe.language" => &mut config.cohere_transcribe.language,
        "funasr_nano.language" => &mut config.funasr_nano.language,
        _ => return None,
    })
}
