//! The generator over a small source of its own: which fields are files, how nested ones are named, and the table it
//! writes.

use super::{is_option_string, render, walk, Structs};

fn structs(src: &str) -> Structs {
    let mut structs = Structs::new();
    for item in syn::parse_file(src).expect("Rust").items {
        if let syn::Item::Struct(item) = item {
            if let syn::Fields::Named(fields) = item.fields {
                let fields = fields
                    .named
                    .into_iter()
                    .filter_map(|field| Some((field.ident?.to_string(), field.ty)))
                    .collect();
                structs.insert(item.ident.to_string(), fields);
            }
        }
    }
    structs
}

#[test]
fn every_option_string_below_the_root_is_named_by_its_path_and_nothing_else() {
    let structs = structs(
        "pub struct Root { pub whisper: Whisper, pub tokens: Option<String>, pub num_threads: i32, \
         pub feat: sys::Feature }\n\
         pub struct Whisper { pub encoder: Option<String>, pub tail_paddings: i32, pub lang: Option<Vec<String>> }",
    );
    let mut paths = Vec::new();
    walk(&structs, "Root", "", &mut paths).expect("walked");
    assert_eq!(paths, ["whisper.encoder", "tokens"]);
    assert!(walk(&structs, "Missing", "", &mut Vec::new()).is_err());
}

#[test]
fn only_option_of_string_is_a_path() {
    let ty = |src: &str| syn::parse_str::<syn::Type>(src).expect("a type");
    assert!(is_option_string(&ty("Option<String>")));
    assert!(is_option_string(&ty("std::option::Option<String>")));
    assert!(!is_option_string(&ty("String")));
    assert!(!is_option_string(&ty("Option<i32>")));
    assert!(!is_option_string(&ty("Option<Vec<String>>")));
}

#[test]
fn the_table_says_it_is_generated_and_maps_each_path_to_its_field() {
    let text = render(
        "1.2.3",
        &["whisper.encoder".to_owned(), "tokens".to_owned()],
        &["kokoro.model".to_owned()],
        &["silero_vad.model".to_owned()],
        &["whisper.language".to_owned()],
    );
    assert!(text.starts_with("//! Generated by `cargo xtask sherpa-libs --pin`"));
    assert!(text.contains("sherpa-onnx 1.2.3"));
    assert!(text.contains("\"whisper.encoder\" => &mut config.whisper.encoder,"));
    assert!(text.contains("\"kokoro.model\" => &mut config.kokoro.model,"));
    assert!(text.contains("fn vad_field"));
    assert!(text.contains("\"silero_vad.model\" => &mut config.silero_vad.model,"));
    assert!(text.contains("fn stt_option"));
    assert!(text.contains("\"whisper.language\" => &mut config.whisper.language,"));
}
